before_install:
- sudo apt-get update
- sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
script:
- cd report
- mkdir _build
- pdflatex -interaction=nonstopmode -output-directory=./_build FakeNewsChallenge.tex
- bibtex ./_build/FakeNewsChallenge
- pdflatex -interaction=nonstopmode -output-directory=./_build FakeNewsChallenge.tex
deploy:
  provider: releases
  api_key:
    secure: 
  file:
    - ./_build/FakeNewsChallenge.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
